select * FROM Faculties;
SELECT * FROM Departments;
SELECT * FROM GROUPS;
SELECT * FROM Curators;
SELECT * FROM GroupsCurators;
SELECT * FROM Subjects;
SELECT * FROM Teachers;
SELECT * FROM Lectures;
SELECT * FROM GroupsLectures;